"""add_mazo_column

Revision ID: 1bc7ce276619
Revises: f3071e13a816
Create Date: 2026-08-15 14:46:28.851678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc7ce276619'
down_revision: Union[str, Sequence[str], None] = 'f3071e13a816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_cartas', sa.Column('mazo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_cartas', 'mazo')
    # ### end Alembic commands ###
