"""agrega_ejecucion_id

Revision ID: d457bcac1480
Revises: e233ee21c9fc
Create Date: 2026-08-15 19:56:50.579431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd457bcac1480'
down_revision: Union[str, Sequence[str], None] = 'e233ee21c9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_precios', sa.Column('ejecucion_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_fact_precios_ejecucion_id'), 'fact_precios', ['ejecucion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_precios_ejecucion_id'), table_name='fact_precios')
    op.drop_column('fact_precios', 'ejecucion_id')
    # ### end Alembic commands ###
