"""Esquema Inicial con Estados

Revision ID: f3071e13a816
Revises: 
Create Date: 2026-08-13 22:41:18.542090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3071e13a816'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_cartas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('edicion_preferida', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('dim_tiendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('url_base', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('fact_precios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carta_id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('edicion', sa.String(), nullable=True),
    sa.Column('idioma', sa.String(length=2), nullable=True),
    sa.Column('acabado', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=True),
    sa.Column('variantes', sa.String(), nullable=True),
    sa.Column('precio_clp', sa.Float(), nullable=False),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carta_id'], ['dim_cartas.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['dim_tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_precios')
    op.drop_table('dim_tiendas')
    op.drop_table('dim_cartas')
    # ### end Alembic commands ###
